.TH "mmeec" "1" "0.1.1" "Pozsar Zsolt" "Environment characteristics editor"
.SH "NAME"
.LP 
MMEEC \- Environment characteristics editor
.SH "SYNTAX"
.LP
mmeec [-h | --help | -v | --version]
.br 
.SH OPTIONS
.TP
.B \-h \-\-help
Write useable parameters to console.
.TP
.B \-v \-\-version
Write version and build information to console.
.br
.SH "DESCRIPTION"
.LP 
It is an remote editor for environment characteristics configuration
file of MM3D (>v0.3) and MM5D growing house controllers.
.br
This program is free software: you can redistribute it and/or modify it
under the terms of the European Union Public License 1.1 version.
.br
.SH "FILE"
.TP
.B /etc/mmeec.ini
configuration file
.TP
.B /usr/local/etc/mmeec.ini
configuration file
.TP
.B /tmp/mmeec.tmp
temporary file
.TP
.B ~/.config/mmeec.ini
user's configuration file
.br
.SH "EXIT STATUS"
.TP
.B 0
Normal exit.
.TP
.B 1
There are one or more bad parameters in command line.
.TP
.B 2
Too small terminal, minimal size is 80x25 characters.
.TP
.B 3
Cannot read configuration file.
.TP
.B 4
Cannot read temporary file.
.TP
.B 5
Cannot write temporary file.
.br
.SH "AUTHOR"
.LP 
Pozsar Zsolt
.br
Web:    <http://www.szerafingomba.hu/softwares/>
.br
E-mail: <pozsar.zsolt@szerafingomba.hu>

