# $FreeBSD$

PORTNAME=	mmeec
PORTVERSION=	0.1
CATEGORIES=	?
MASTER_SITES=	http://www.szerafingomba.hu/softwares/mmeec/

MAINTAINER=	pozsar.zsolt@szerafingomba.hu
COMMENT=	Environment characteristics editor

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)
