#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/mmeec -a -d /usr/share/doc/mmeec ]; then
    ln -sf /usr/share/doc/mmeec /usr/doc/mmeec
  fi
fi
# End automatically added section
