#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/libmmapi -a -d /usr/share/doc/libmmapi ]; then
    ln -sf /usr/share/doc/libmmapi /usr/doc/libmmapi
  fi
fi
# End automatically added section
