{ +--------------------------------------------------------------------------+ }
{ | MMEEC v0.1 * Environment characteristics editor                          | }
{ | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>         | }
{ | saveinifile.pas                                                          | }
{ | Save configuration to ini file                                           | }
{ +--------------------------------------------------------------------------+ }

//   This program is free software: you can redistribute it and/or modify it
// under the terms of the European Union Public License 1.1 version.
//
//   This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.

// save environment characteristics file
function saveinifile(filename: string): boolean;
var
  iif: text;
const
  HEADER1='; +----------------------------------------------------------------------------+';
  HEADER2='; | MMEEC v0.1 * Environment characteristics editor                            |';
  HEADER3='; | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>           |';
  HEADER4='; | envir.ini                                                                  |';
  HEADER5='; | growing environment characteristics                                        |';

begin
  saveinifile:=true;
  try
    assign(iif,filename);
    rewrite(iif);
    writeln(iif,HEADER1);
    writeln(iif,HEADER2);
    writeln(iif,HEADER3);
    writeln(iif,HEADER4);
    writeln(iif,HEADER5);
    writeln(iif,HEADER1);
    writeln(iif,'');
    writeln(iif,'[hyphae]');
    writeln(iif,'; humidifier');
    writeln(iif,'humidity_min=',hhummin);
    writeln(iif,'humidifier_on=',hhumon);
    writeln(iif,'humidifier_off=',hhumoff);
    writeln(iif,'humidity_max=',hhummax);
    writeln(iif,'humidifier_disable_00=',hhumdis[0]);
    writeln(iif,'humidifier_disable_01=',hhumdis[1]);
    writeln(iif,'humidifier_disable_02=',hhumdis[2]);
    writeln(iif,'humidifier_disable_03=',hhumdis[3]);
    writeln(iif,'humidifier_disable_04=',hhumdis[4]);
    writeln(iif,'humidifier_disable_05=',hhumdis[5]);
    writeln(iif,'humidifier_disable_06=',hhumdis[6]);
    writeln(iif,'humidifier_disable_07=',hhumdis[7]);
    writeln(iif,'humidifier_disable_08=',hhumdis[8]);
    writeln(iif,'humidifier_disable_09=',hhumdis[9]);
    writeln(iif,'humidifier_disable_10=',hhumdis[10]);
    writeln(iif,'humidifier_disable_11=',hhumdis[11]);
    writeln(iif,'humidifier_disable_12=',hhumdis[12]);
    writeln(iif,'humidifier_disable_13=',hhumdis[13]);
    writeln(iif,'humidifier_disable_14=',hhumdis[14]);
    writeln(iif,'humidifier_disable_15=',hhumdis[15]);
    writeln(iif,'humidifier_disable_16=',hhumdis[16]);
    writeln(iif,'humidifier_disable_17=',hhumdis[17]);
    writeln(iif,'humidifier_disable_18=',hhumdis[18]);
    writeln(iif,'humidifier_disable_19=',hhumdis[19]);
    writeln(iif,'humidifier_disable_20=',hhumdis[20]);
    writeln(iif,'humidifier_disable_21=',hhumdis[21]);
    writeln(iif,'humidifier_disable_22=',hhumdis[22]);
    writeln(iif,'humidifier_disable_23=',hhumdis[23]);
    writeln(iif,'');
    writeln(iif,'; heaters');
    writeln(iif,'temperature_min=',htempmin);
    writeln(iif,'heater_on=',htempon);
    writeln(iif,'heater_off=',htempoff);
    writeln(iif,'temperature_max=',htempmax);
    writeln(iif,'heater_disable_00=',hheaterdis[0]);
    writeln(iif,'heater_disable_01=',hheaterdis[1]);
    writeln(iif,'heater_disable_02=',hheaterdis[2]);
    writeln(iif,'heater_disable_03=',hheaterdis[3]);
    writeln(iif,'heater_disable_04=',hheaterdis[4]);
    writeln(iif,'heater_disable_05=',hheaterdis[5]);
    writeln(iif,'heater_disable_06=',hheaterdis[6]);
    writeln(iif,'heater_disable_07=',hheaterdis[7]);
    writeln(iif,'heater_disable_08=',hheaterdis[8]);
    writeln(iif,'heater_disable_09=',hheaterdis[9]);
    writeln(iif,'heater_disable_10=',hheaterdis[10]);
    writeln(iif,'heater_disable_11=',hheaterdis[11]);
    writeln(iif,'heater_disable_12=',hheaterdis[12]);
    writeln(iif,'heater_disable_13=',hheaterdis[13]);
    writeln(iif,'heater_disable_14=',hheaterdis[14]);
    writeln(iif,'heater_disable_15=',hheaterdis[15]);
    writeln(iif,'heater_disable_16=',hheaterdis[16]);
    writeln(iif,'heater_disable_17=',hheaterdis[17]);
    writeln(iif,'heater_disable_18=',hheaterdis[18]);
    writeln(iif,'heater_disable_19=',hheaterdis[19]);
    writeln(iif,'heater_disable_20=',hheaterdis[20]);
    writeln(iif,'heater_disable_21=',hheaterdis[21]);
    writeln(iif,'heater_disable_22=',hheaterdis[22]);
    writeln(iif,'heater_disable_23=',hheaterdis[23]);
    writeln(iif,'');
    writeln(iif,'; lights');
    writeln(iif,'light_on1=',hlightson1);
    writeln(iif,'light_off1=',hlightsoff1);
    writeln(iif,'light_on2=',hlightson2);
    writeln(iif,'light_off2=',hlightsoff2);
    writeln(iif,'');
    writeln(iif,'; ventillators');
    writeln(iif,'vent_on=',hventon);
    writeln(iif,'vent_off=',hventoff);
    writeln(iif,'vent_disable_00=',hventdis[0]);
    writeln(iif,'vent_disable_01=',hventdis[1]);
    writeln(iif,'vent_disable_02=',hventdis[2]);
    writeln(iif,'vent_disable_03=',hventdis[3]);
    writeln(iif,'vent_disable_04=',hventdis[4]);
    writeln(iif,'vent_disable_05=',hventdis[5]);
    writeln(iif,'vent_disable_06=',hventdis[6]);
    writeln(iif,'vent_disable_07=',hventdis[7]);
    writeln(iif,'vent_disable_08=',hventdis[8]);
    writeln(iif,'vent_disable_09=',hventdis[9]);
    writeln(iif,'vent_disable_10=',hventdis[10]);
    writeln(iif,'vent_disable_11=',hventdis[11]);
    writeln(iif,'vent_disable_12=',hventdis[12]);
    writeln(iif,'vent_disable_13=',hventdis[13]);
    writeln(iif,'vent_disable_14=',hventdis[14]);
    writeln(iif,'vent_disable_15=',hventdis[15]);
    writeln(iif,'vent_disable_16=',hventdis[16]);
    writeln(iif,'vent_disable_17=',hventdis[17]);
    writeln(iif,'vent_disable_18=',hventdis[18]);
    writeln(iif,'vent_disable_19=',hventdis[19]);
    writeln(iif,'vent_disable_20=',hventdis[20]);
    writeln(iif,'vent_disable_21=',hventdis[21]);
    writeln(iif,'vent_disable_22=',hventdis[22]);
    writeln(iif,'vent_disable_23=',hventdis[23]);
    writeln(iif,'vent_disablelowtemp_00=',hventdislowtemp[0]);
    writeln(iif,'vent_disablelowtemp_01=',hventdislowtemp[1]);
    writeln(iif,'vent_disablelowtemp_02=',hventdislowtemp[2]);
    writeln(iif,'vent_disablelowtemp_03=',hventdislowtemp[3]);
    writeln(iif,'vent_disablelowtemp_04=',hventdislowtemp[4]);
    writeln(iif,'vent_disablelowtemp_05=',hventdislowtemp[5]);
    writeln(iif,'vent_disablelowtemp_06=',hventdislowtemp[6]);
    writeln(iif,'vent_disablelowtemp_07=',hventdislowtemp[7]);
    writeln(iif,'vent_disablelowtemp_08=',hventdislowtemp[8]);
    writeln(iif,'vent_disablelowtemp_09=',hventdislowtemp[9]);
    writeln(iif,'vent_disablelowtemp_10=',hventdislowtemp[10]);
    writeln(iif,'vent_disablelowtemp_11=',hventdislowtemp[11]);
    writeln(iif,'vent_disablelowtemp_12=',hventdislowtemp[12]);
    writeln(iif,'vent_disablelowtemp_13=',hventdislowtemp[13]);
    writeln(iif,'vent_disablelowtemp_14=',hventdislowtemp[14]);
    writeln(iif,'vent_disablelowtemp_15=',hventdislowtemp[15]);
    writeln(iif,'vent_disablelowtemp_16=',hventdislowtemp[16]);
    writeln(iif,'vent_disablelowtemp_17=',hventdislowtemp[17]);
    writeln(iif,'vent_disablelowtemp_18=',hventdislowtemp[18]);
    writeln(iif,'vent_disablelowtemp_19=',hventdislowtemp[19]);
    writeln(iif,'vent_disablelowtemp_20=',hventdislowtemp[20]);
    writeln(iif,'vent_disablelowtemp_21=',hventdislowtemp[21]);
    writeln(iif,'vent_disablelowtemp_22=',hventdislowtemp[22]);
    writeln(iif,'vent_disablelowtemp_23=',hventdislowtemp[23]);
    writeln(iif,'vent_lowtemp=',hventlowtemp);
    writeln(iif,'');
    writeln(iif,'[mushroom]');
    writeln(iif,'; humidifier');
    writeln(iif,'humidity_min=',mhummin);
    writeln(iif,'humidifier_on=',mhumon);
    writeln(iif,'humidifier_off=',mhumoff);
    writeln(iif,'humidity_max=',mhummax);
    writeln(iif,'humidifier_disable_00=',mhumdis[0]);
    writeln(iif,'humidifier_disable_01=',mhumdis[1]);
    writeln(iif,'humidifier_disable_02=',mhumdis[2]);
    writeln(iif,'humidifier_disable_03=',mhumdis[3]);
    writeln(iif,'humidifier_disable_04=',mhumdis[4]);
    writeln(iif,'humidifier_disable_05=',mhumdis[5]);
    writeln(iif,'humidifier_disable_06=',mhumdis[6]);
    writeln(iif,'humidifier_disable_07=',mhumdis[7]);
    writeln(iif,'humidifier_disable_08=',mhumdis[8]);
    writeln(iif,'humidifier_disable_09=',mhumdis[9]);
    writeln(iif,'humidifier_disable_10=',mhumdis[10]);
    writeln(iif,'humidifier_disable_11=',mhumdis[11]);
    writeln(iif,'humidifier_disable_12=',mhumdis[12]);
    writeln(iif,'humidifier_disable_13=',mhumdis[13]);
    writeln(iif,'humidifier_disable_14=',mhumdis[14]);
    writeln(iif,'humidifier_disable_15=',mhumdis[15]);
    writeln(iif,'humidifier_disable_16=',mhumdis[16]);
    writeln(iif,'humidifier_disable_17=',mhumdis[17]);
    writeln(iif,'humidifier_disable_18=',mhumdis[18]);
    writeln(iif,'humidifier_disable_19=',mhumdis[19]);
    writeln(iif,'humidifier_disable_20=',mhumdis[20]);
    writeln(iif,'humidifier_disable_21=',mhumdis[21]);
    writeln(iif,'humidifier_disable_22=',mhumdis[22]);
    writeln(iif,'humidifier_disable_23=',mhumdis[23]);
    writeln(iif,'');
    writeln(iif,'; heaters');
    writeln(iif,'temperature_min=',mtempmin);
    writeln(iif,'heater_on=',mtempon);
    writeln(iif,'heater_off=',mtempoff);
    writeln(iif,'temperature_max=',mtempmax);
    writeln(iif,'heater_disable_00=',mheaterdis[0]);
    writeln(iif,'heater_disable_01=',mheaterdis[1]);
    writeln(iif,'heater_disable_02=',mheaterdis[2]);
    writeln(iif,'heater_disable_03=',mheaterdis[3]);
    writeln(iif,'heater_disable_04=',mheaterdis[4]);
    writeln(iif,'heater_disable_05=',mheaterdis[5]);
    writeln(iif,'heater_disable_06=',mheaterdis[6]);
    writeln(iif,'heater_disable_07=',mheaterdis[7]);
    writeln(iif,'heater_disable_08=',mheaterdis[8]);
    writeln(iif,'heater_disable_09=',mheaterdis[9]);
    writeln(iif,'heater_disable_10=',mheaterdis[10]);
    writeln(iif,'heater_disable_11=',mheaterdis[11]);
    writeln(iif,'heater_disable_12=',mheaterdis[12]);
    writeln(iif,'heater_disable_13=',mheaterdis[13]);
    writeln(iif,'heater_disable_14=',mheaterdis[14]);
    writeln(iif,'heater_disable_15=',mheaterdis[15]);
    writeln(iif,'heater_disable_16=',mheaterdis[16]);
    writeln(iif,'heater_disable_17=',mheaterdis[17]);
    writeln(iif,'heater_disable_18=',mheaterdis[18]);
    writeln(iif,'heater_disable_19=',mheaterdis[19]);
    writeln(iif,'heater_disable_20=',mheaterdis[20]);
    writeln(iif,'heater_disable_21=',mheaterdis[21]);
    writeln(iif,'heater_disable_22=',mheaterdis[22]);
    writeln(iif,'heater_disable_23=',mheaterdis[23]);
    writeln(iif,'');
    writeln(iif,'; lights');
    writeln(iif,'light_on1=',mlightson1);
    writeln(iif,'light_off1=',mlightsoff1);
    writeln(iif,'light_on2=',mlightson2);
    writeln(iif,'light_off2=',mlightsoff2);
    writeln(iif,'');
    writeln(iif,'; ventillators');
    writeln(iif,'vent_on=',mventon);
    writeln(iif,'vent_off=',mventoff);
    writeln(iif,'vent_disable_00=',mventdis[0]);
    writeln(iif,'vent_disable_01=',mventdis[1]);
    writeln(iif,'vent_disable_02=',mventdis[2]);
    writeln(iif,'vent_disable_03=',mventdis[3]);
    writeln(iif,'vent_disable_04=',mventdis[4]);
    writeln(iif,'vent_disable_05=',mventdis[5]);
    writeln(iif,'vent_disable_06=',mventdis[6]);
    writeln(iif,'vent_disable_07=',mventdis[7]);
    writeln(iif,'vent_disable_08=',mventdis[8]);
    writeln(iif,'vent_disable_09=',mventdis[9]);
    writeln(iif,'vent_disable_10=',mventdis[10]);
    writeln(iif,'vent_disable_11=',mventdis[11]);
    writeln(iif,'vent_disable_12=',mventdis[12]);
    writeln(iif,'vent_disable_13=',mventdis[13]);
    writeln(iif,'vent_disable_14=',mventdis[14]);
    writeln(iif,'vent_disable_15=',mventdis[15]);
    writeln(iif,'vent_disable_16=',mventdis[16]);
    writeln(iif,'vent_disable_17=',mventdis[17]);
    writeln(iif,'vent_disable_18=',mventdis[18]);
    writeln(iif,'vent_disable_19=',mventdis[19]);
    writeln(iif,'vent_disable_20=',mventdis[20]);
    writeln(iif,'vent_disable_21=',mventdis[21]);
    writeln(iif,'vent_disable_22=',mventdis[22]);
    writeln(iif,'vent_disable_23=',mventdis[23]);
    writeln(iif,'vent_disablelowtemp_00=',mventdislowtemp[0]);
    writeln(iif,'vent_disablelowtemp_01=',mventdislowtemp[1]);
    writeln(iif,'vent_disablelowtemp_02=',mventdislowtemp[2]);
    writeln(iif,'vent_disablelowtemp_03=',mventdislowtemp[3]);
    writeln(iif,'vent_disablelowtemp_04=',mventdislowtemp[4]);
    writeln(iif,'vent_disablelowtemp_05=',mventdislowtemp[5]);
    writeln(iif,'vent_disablelowtemp_06=',mventdislowtemp[6]);
    writeln(iif,'vent_disablelowtemp_07=',mventdislowtemp[7]);
    writeln(iif,'vent_disablelowtemp_08=',mventdislowtemp[8]);
    writeln(iif,'vent_disablelowtemp_09=',mventdislowtemp[9]);
    writeln(iif,'vent_disablelowtemp_10=',mventdislowtemp[10]);
    writeln(iif,'vent_disablelowtemp_11=',mventdislowtemp[11]);
    writeln(iif,'vent_disablelowtemp_12=',mventdislowtemp[12]);
    writeln(iif,'vent_disablelowtemp_13=',mventdislowtemp[13]);
    writeln(iif,'vent_disablelowtemp_14=',mventdislowtemp[14]);
    writeln(iif,'vent_disablelowtemp_15=',mventdislowtemp[15]);
    writeln(iif,'vent_disablelowtemp_16=',mventdislowtemp[16]);
    writeln(iif,'vent_disablelowtemp_17=',mventdislowtemp[17]);
    writeln(iif,'vent_disablelowtemp_18=',mventdislowtemp[18]);
    writeln(iif,'vent_disablelowtemp_19=',mventdislowtemp[19]);
    writeln(iif,'vent_disablelowtemp_20=',mventdislowtemp[20]);
    writeln(iif,'vent_disablelowtemp_21=',mventdislowtemp[21]);
    writeln(iif,'vent_disablelowtemp_22=',mventdislowtemp[22]);
    writeln(iif,'vent_disablelowtemp_23=',mventdislowtemp[23]);
    writeln(iif,'vent_lowtemp=',mventlowtemp);
    writeln(iif,'');
    close(iif);
  except
    saveinifile:=false;
  end;
end;
